# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in deepthought.gemspec
gemspec

gem "rake", "~> 13.0"
gem 'colorize', '~> 0.8.1'
gem "minitest", "~> 5.0"
